### ISSUE TITLE
️🛠 - Add (hidden) EPK page

### ISSUE THREAD

**Issue by maxwellmattryan** [maxwellmattryan/apellum.com#10]
### Task description

This will be massively important for people to have quick access to. It should include all relevant things for my EPK plus an option to download a zipped folder of it.

### Requirements

- [x] Add copyably bios section
- [x] Add music section
- [x] Add press section
- [x] Polish UI
- [x] Allow user to download zipped EPK
